### ISSUE TITLE
Beta version button of the beta version redirects user to unknown page

### ISSUE THREAD

**Issue by kimlimjustin** [stanleyowen/lofi-player#48]
**Describe the bug**
If you click the beta version button of the beta version webpage(https://next--lofi-players.netlify.app/), it redirects the user to an unknown page(https://next--next--lofi-players.netlify.app/).

**To Reproduce**
1. Open the [lofi-player website](https://lofi-players.netlify.app/)
2. Open beta version by clicking the "Beta version" button
3. Click the "Beta version" button again
4. See bug

**Expected behavior**
Erm, just disable the button or change it to redirect user to the stable version site

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser Chrome

**Comment by stanleyowen** [comment]
Thanks for the report! I will soon working on this issue.
